### ISSUE TITLE
Warhead lua Comments

### ISSUE THREAD

**Issue by Hextopia** [Quaggles/dcs-lua-datamine#3]
It would be helpful to add in the comments from one of the warheads luas that explains what the various values actually mean (explosive mass is essentially damage and is measured in equivalent TNT weight in kg, penetration values, penetration damage multiplier, concrete damage coefficients, etc.)

**Comment by Quaggles** [comment]
Fixed in ce49124aac0846830a525f39c467167a78a5ff97 check https://github.com/Quaggles/dcs-lua-datamine#_gwarheads
