### ISSUE TITLE
Missing units from output

### ISSUE THREAD

**Issue by Pfhoenix** [Quaggles/dcs-lua-datamine#5]
Specifically, the Ka-52 is missing from _G/db/Units output. Is there something different in how the Ka-52 is handled within DCS? It has a unit payload entry in the game's mission editor script files.

**Comment by Quaggles** [comment]
The exporter scans tables registered in the DCS lua database and exports those, if the developers did not register the Ka-52 as a unit in the database it won't show up in the Units export. Looking back at my DCS 2.5.6 Scripts folder backup there was an entry for it but it must have been disabled from being included in the database somewhere, now that the /Scripts/Database lua files are hidden there is no way of seeing it.

[\Scripts\Database\helicopters\Ka-52.lua](https://github.com/Quaggles/dcs-lua-datamine/files/9034212/Ka-52.txt)

There are other remenants of it still in the game files such as [the sensor entry](https://github.com/Quaggles/dcs-lua-datamine/blob/master/_G/db/Sensors/Sensor/Ka-52%20FLIR.lua) (which is still registered in the DB so the exporter finds), the model even still exists but it looks quite old ("DCS World\Bazar\World\Shapes\ka-52.edm"):

![image](https://user-images.githubusercontent.com/8382945/177029336-fe623775-c249-4f87-9ce9-d6360b74f2fe.png)
