### ISSUE TITLE
Possible table addition

### ISSUE THREAD

**Issue by Rolln-dev** [Quaggles/dcs-lua-datamine#7]
Is there a ['weapons']['adapters'] table in _G?

For example in the BRU_33A.lua file there is _unique_resource_name reference to weapons.adapters.BRU_33A so looking to see if the adapters table exists and if so, what's in it.

```lua
_G["Pylons"]["BRU_33A"] = {
	IsAdapter = true,
	ShapeName = "BRU_33A",
	_unique_resource_name = "weapons.adapters.BRU_33A",
	index = "Redacted",
	name = "BRU_33A",
	shape_table_data = { {
			file = "BRU_33A",
			fire = { 0, 1 },
			index = "Redacted",
			life = 60,
			name = "BRU_33A",
			username = "BRU_33A"
		} },
	ws_type = { 4, 15, 47, "Redacted" }
}
```

**Comment by Quaggles** [comment]
I did a bit of looking around `_unique_resource_name` seems to be an index/key into the table `_G.resource_by_unique_name`

So in this example `_G.resource_by_unique_name["weapons.adapters.BRU_33A"]` results in the same data as the pylon you posted:
```lua
{
  IsAdapter = true,
  ShapeName = "BRU_33A",
  _unique_resource_name = "weapons.adapters.BRU_33A",
  index = 1392,
  name = "BRU_33A",
  shape_table_data = { {
      file = "BRU_33A",
      fire = { 0, 1 },
      index = 1392,
      life = 60,
      name = "BRU_33A",
      username = "BRU_33A"
    } },
  ws_type = { 4, 15, 47, 1392 }
}
```

So it looks like `_G.resource_by_unique_name` is just another way of organising tables from across the lua database into one big table which is used somewhere in DCS

**Comment by Rolln-dev** [comment]
Thanks for looking into this and sorry for my late reply.  

I have been putting together my own weight table/db which is proving to be challenging normalizing the data.  Was hoping I could have used `weapons.adapters.`, `weapons.droptanks.`, `weapons.bombs.`, etc but doesn't look like all items are in there. It looks like `resource_by_unique_name` may not contain all the weapons/containers/adapters/etc.  

Thanks again!
